### ISSUE TITLE
How to make tensorflow use GPUs with TFAMI.v2

### ISSUE THREAD

**Issue by avostryakov** [ritchieng/tensorflow-aws-ami#4]
When I started tensorflow with TFAMI.v2 on g2.8xlarge I saw the following message:
I tensorflow/core/common_runtime/gpu/gpu_device.cc:813] Ignoring gpu device (device: 0, name: GRID K520, pci bus id: 0000:00:03.0) with Cuda compute capability 3.0. The minimum required Cuda capability is 3.5

I checked with nvidia-smi and top commands: the code works on CPU so it's really ignores GPUs. Can I do something to make it works on  g2.8xlarge? to set environment variable or something else?

**Comment by avostryakov** [comment]
I can add that N. California ami-5ce2ab3c (TFAMI) with installed tensorfow 0.10 works correctly. I think the problem can be in wrong version of tensorflow or cuda 8.

**Comment by ritchieng** [comment]
@avostryakov I'll investigate this. I believe it's because I've been testing heavily on `p2 instances` recently and not `g2.8x`. But it's most likely due to the compiling of TensorFlow when I built it. Meanwhile I believe for the price of `g2.8x`, you can go for `p2` instances with higher performance.

**Comment by ritchieng** [comment]
@avostryakov This would be fixed in the new v1.3 slated to be released soon.

In the meantime, you can use `p2 instance` with `TFAMI.v2` or `g2 instance` with `TFAMI`.

Sorry for the inconvenience!

**Comment by avostryakov** [comment]
Thank you!
