### ISSUE TITLE
permission denied (publickey)

### ISSUE THREAD

**Issue by nicolaifsf** [ritchieng/tensorflow-aws-ami#6]
Hey! I'm having issues connecting to my p2.x instance on aws using your AMI.
I'm sshing with
`ssh -i <file>.pem ec2-user@<public IP> `and it gives me permission denied(public key). I don't seem to be having any issues connecting using the same method to the default amazon linux image, so I was wondering if you might be able to share some pointers.
Thank you for your time!

**Comment by ritchieng** [comment]
Hi @nicolaifsf, this has nothing to do with this AMI :) You're facing this issue because you did not set up your key properly. 

You should be in the directory of your key where you would have downloaded from Amazon such as `mykey.pem`. 

Once you're in that directory, you need to have a command that resembles this: `ssh -i mykey.pem ubuntu@ec2-54-196-180-225.compute-1.amazonaws.com`.

You can find the `ec2` part when you start your instance.

**Comment by nicolaifsf** [comment]
actually I don't think it has to relate with me being in the same dir as my pem key so long as the path is correct. my issue was that I thought that it was based off of the base amazon linux image and so was using `ec2-user@<IP>` in order to log in. I also just noticed that I had some typos in my comment as I had use "<>" in order to specify certain things.

Logging in with ubuntu as the user solved it. thanks!

**Comment by ritchieng** [comment]
Nice. If you face any problems, do check out the FAQs, typically a `sudo reboot` would make it work.
